apiVersion: apps/v1
kind: Service
metadata:
  labels:
    app: hello-two
  name: hello-two
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-two
  sessionAffinity: None
  type: LoadBalancer
